In [1]:
import numpy as np
from environment import GridWorld
from agent import *

In [2]:
reward_matrix = np.zeros((10,10))
reward_matrix[3,3] = -1
reward_matrix[4,5] = -1
reward_matrix[4,6] = -1
reward_matrix[5,5] = 1
reward_matrix[5,6] = -1
reward_matrix[5,8] = -1
reward_matrix[6,8] = -1
reward_matrix[7,3] = -1
reward_matrix[7,5] = -1
reward_matrix[7,6] = -1
env = GridWorld(reward_matrix)
agt = DPAgent(env)

In [3]:
env.reward_matrix

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., nan, nan, nan, nan,  0., nan, nan, nan,  0.],
       [ 0.,  0.,  0., -1., nan,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., nan, -1., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., nan,  1., -1.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0., nan,  0.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  0., -1., nan, -1., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [4]:
for i in range(4):
    print(env.get_next_state((4,5),i))

(3, 5)
(4, 6)
(5, 5)
(4, 5)


In [5]:
agt.policy_evaluation()

Policy Evaluation:
 [[-0.06 -0.05 -0.04 -0.05 -0.08 -0.11 -0.09 -0.09 -0.1  -0.14]
 [-0.09 -0.05 -0.05 -0.06 -0.1  -0.2  -0.11 -0.09 -0.11 -0.2 ]
 [-0.19   nan   nan   nan   nan -0.58   nan   nan   nan -0.42]
 [-0.34 -0.61 -1.26 -2.88   nan -1.22 -1.48 -1.19 -1.   -0.78]
 [-0.35 -0.5  -0.84 -1.33   nan -2.15 -2.67 -1.62 -1.47 -1.18]
 [-0.33 -0.42 -0.63 -0.88   nan  0.94 -2.2  -1.87 -2.74 -1.68]
 [-0.32 -0.42 -0.67 -1.07   nan -1.02 -1.71 -1.76 -2.71 -1.67]
 [-0.32 -0.45 -0.87 -2.13   nan -2.73 -2.64 -1.54 -1.42 -1.18]
 [-0.3  -0.38 -0.6  -0.95 -0.86 -1.3  -1.32 -1.02 -0.9  -0.83]
 [-0.29 -0.34 -0.48 -0.64 -0.71 -0.87 -0.89 -0.79 -0.72 -0.7 ]]


In [6]:
agt.policy_iteration()

Policy Evaluation:
 [[-0.06 -0.05 -0.04 -0.05 -0.08 -0.11 -0.09 -0.09 -0.1  -0.14]
 [-0.09 -0.05 -0.05 -0.06 -0.1  -0.2  -0.11 -0.09 -0.11 -0.2 ]
 [-0.19   nan   nan   nan   nan -0.58   nan   nan   nan -0.42]
 [-0.34 -0.61 -1.26 -2.88   nan -1.22 -1.48 -1.19 -1.   -0.78]
 [-0.35 -0.5  -0.84 -1.33   nan -2.15 -2.67 -1.62 -1.47 -1.18]
 [-0.33 -0.42 -0.63 -0.88   nan  0.94 -2.2  -1.87 -2.74 -1.68]
 [-0.32 -0.42 -0.67 -1.07   nan -1.02 -1.71 -1.76 -2.71 -1.67]
 [-0.32 -0.45 -0.87 -2.13   nan -2.73 -2.64 -1.54 -1.42 -1.18]
 [-0.3  -0.38 -0.6  -0.95 -0.86 -1.3  -1.32 -1.02 -0.9  -0.83]
 [-0.29 -0.34 -0.48 -0.64 -0.71 -0.87 -0.89 -0.79 -0.72 -0.7 ]]
Policy Evaluation:
 [[-0.   -0.   -0.   -0.   -0.   -0.   -0.   -0.   -0.   -0.  ]
 [-0.   -0.   -0.   -0.   -0.   -0.   -0.   -0.   -0.   -0.  ]
 [-0.     nan   nan   nan   nan -0.     nan   nan   nan -0.  ]
 [-0.   -0.   -0.   -1.     nan -0.   -0.   -0.   -0.   -0.  ]
 [-0.   -0.   -0.   -0.     nan -0.1  -1.   -0.   -0.   -0.  ]
 [-0.   -0.   

In [7]:
agt.policy

[[[0.0, 0.5, 0.5, 0.0],
  [0.0, 0.5, 0.5, 0.0],
  [0.0, 0.5, 0.5, 0.0],
  [0.0, 0.5, 0.5, 0.0],
  [0.0, 0.5, 0.5, 0.0],
  [0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.5, 0.5],
  [0.0, 0.3333333333333333, 0.3333333333333333, 0.3333333333333333],
  [0.0, 0.5, 0.5, 0.0],
  [0.0, 0.0, 1.0, 0.0]],
 [[0.0, 1.0, 0.0, 0.0],
  [0.0, 1.0, 0.0, 0.0],
  [0.0, 1.0, 0.0, 0.0],
  [0.0, 1.0, 0.0, 0.0],
  [0.0, 1.0, 0.0, 0.0],
  [0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 1.0],
  [0.0, 0.5, 0.0, 0.5],
  [0.0, 1.0, 0.0, 0.0],
  [0.0, 0.0, 1.0, 0.0]],
 [[1.0, 0.0, 0.0, 0.0],
  None,
  None,
  None,
  None,
  [0.0, 0.0, 1.0, 0.0],
  None,
  None,
  None,
  [0.0, 0.0, 1.0, 0.0]],
 [[0.3333333333333333, 0.3333333333333333, 0.3333333333333333, 0.0],
  [0.0, 0.5, 0.5, 0.0],
  [0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.5, 0.5],
  None,
  [0.0, 1.0, 0.0, 0.0],
  [0.0, 1.0, 0.0, 0.0],
  [0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.5, 0.5],
  [0.0, 0.0, 0.5, 0.5]],
 [[0.0, 0.5, 0.5, 0.0],
  [0.0, 0.5, 0.5, 0.0],
  [0.0, 0.0, 1.0, 0.0],
  