## Example 4.1

Let \{0,1,2,3\} denote  the actions \{up, right, down, left\} respectively.

In [1]:
import numpy as np
class gridworld:
    def __init__(self):
        self.terminal_state = [0,15]
        self.action = [0,1,2,3]
        self.value = np.zeros(16)
        self.reward = -1 
    
    def next_state(self, s, a):
        if s in self.terminal_state:
           return s
        if a == 0:
            s = s - 4 if s >= 4 else s  
        elif a == 1:
            s = s + 1 if (s+1)%4 != 0 else s
        elif a == 2:
            s = s + 4 if (s+4) < 16 else s
        elif a == 3:
            s = s - 1 if s % 4 !=0 else s
        return s
     
    def policy_evaluation(self):
         k=0
         while True:
             delta = 0
             v_new = np.zeros(16)
             for s in range(16):
                 v = 0
                 if s in self.terminal_state:
                     v_new[s] = 0
                 else:
                     v = self.value[s]
                     temp = 0
                     for a in range(4):
                        v_new[s] += 0.25*(-1 + self.value[self.next_state(s,a)])
                 delta = max(delta, abs(v-v_new[s]))
             self.value = v_new
             
             # greedy policy
             policy = np.zeros((16,4))
             for s in range(1,15):
                 vmax = -30
                 nmax = 0
                 for a in range(4):
                     v = self.value[self.next_state(s,a)]
                     if v > vmax:
                         vmax = v
                         nmax = 1
                     elif vmax - v < 0.05:
                         nmax += 1
                 for a in range(4):
                     v = self.value[self.next_state(s,a)]
                     if v == vmax:
                         policy[s,a] = 1/nmax
        
             k += 1
             if k == 1 or k==2 or k==3 or k==10 or k==131:
                print('The state value for %ith iteration:\n' %k, v_new.reshape((4,4)))
                print('The greedy policy for %ith iteration:\n' %k, policy)
             if delta < 0.001:
                 return

        
              


                          


In [2]:
a = gridworld()

In [3]:
a.policy_evaluation()

The state value for 1th iteration:
 [[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
The greedy policy for 1th iteration:
 [[0.   0.   0.   0.  ]
 [0.   0.   0.   1.  ]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [1.   0.   0.   0.  ]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.   0.   1.   0.  ]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.   1.   0.   0.  ]
 [0.   0.   0.   0.  ]]
The state value for 2th iteration:
 [[ 0.   -1.75 -2.   -2.  ]
 [-1.75 -2.   -2.   -2.  ]
 [-2.   -2.   -2.   -1.75]
 [-2.   -2.   -1.75  0.  ]]
The greedy policy for 2th iteration:
 [[0.   0.   0.   0.  ]
 [0.   0.   0.   1.  ]
 [0.   0.   0.   1.  ]
 [0.25 0.25 0.25 0.25]
 [1.   0.   0.   0.  ]
 [0.5  0.   0.   0.5 ]
 [0.25 0.25 0.25 0.25]
 [0.   0.   1.   0.  ]
 [1.   0.   0.   0.  ]
 [0.25 0.25 0.25 0.25]
 [0.   0.5  0.5  0.  ]
 [0.   0.   1.   0.  ]
 [0.25 0.25 0.25 0.25